// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvkJnDJOzoHeLF-h_NSCouwv5mvI3STI',
    appId: '1:1037348525919:web:de16ddf930b36a899d88ea',
    messagingSenderId: '1037348525919',
    projectId: 'kormobd-001',
    authDomain: 'kormobd-001.firebaseapp.com',
    storageBucket: 'kormobd-001.firebasestorage.app',
    measurementId: 'G-NN000LH4ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4VA_cwLl0ei7pIa3inazE-hvOecvkBE',
    appId: '1:1037348525919:android:0aab89b1fed18cc79d88ea',
    messagingSenderId: '1037348525919',
    projectId: 'kormobd-001',
    storageBucket: 'kormobd-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSgdCfHx3Nmhz6Dl7rVL1vmL1RwpYbiw',
    appId: '1:1037348525919:ios:b0f2b16e3bc9b9679d88ea',
    messagingSenderId: '1037348525919',
    projectId: 'kormobd-001',
    storageBucket: 'kormobd-001.firebasestorage.app',
    iosClientId: '1037348525919-u6adnattsmvjprfap1m888j7g0s3o4th.apps.googleusercontent.com',
    iosBundleId: 'com.example.kormobd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdvkJnDJOzoHeLF-h_NSCouwv5mvI3STI',
    appId: '1:1037348525919:web:3b2d5a5caef96adf9d88ea',
    messagingSenderId: '1037348525919',
    projectId: 'kormobd-001',
    authDomain: 'kormobd-001.firebaseapp.com',
    storageBucket: 'kormobd-001.firebasestorage.app',
    measurementId: 'G-PGV8YMYED2',
  );
}
